package AdminDashboard;


import Login_Signup.LoginPage;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.UIManager;

public class AdminDashboardMenu extends javax.swing.JFrame {

    Color defaultColor, clickedColor;
    
    public AdminDashboardMenu() {
        initComponents();
        defaultColor = new Color(13,16,51);
        clickedColor = new Color(240,151,57);
        
        menuPanel1.setBackground(defaultColor);
        menuPanel2.setBackground(defaultColor);
        menuPanel3.setBackground(defaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orangeTitleBar = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        menuIcon = new javax.swing.JLabel();
        subTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashBoardPanel = new javax.swing.JPanel();
        menuPanel1 = new javax.swing.JPanel();
        CRUDPenjualLabel = new javax.swing.JLabel();
        menuPanel2 = new javax.swing.JPanel();
        CRUDPembeliLabel = new javax.swing.JLabel();
        menuPanel3 = new javax.swing.JPanel();
        CRUDKurirLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        whitePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orangeTitleBar.setBackground(new java.awt.Color(240, 151, 57));
        orangeTitleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_35px.png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        orangeTitleBar.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, -1));

        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xbox_menu_50px.png"))); // NOI18N
        orangeTitleBar.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 50));

        subTitleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        subTitleLabel.setText("CRUD Penjual");
        orangeTitleBar.add(subTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-0pocG7FZKpHe7c.png"))); // NOI18N
        orangeTitleBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin Dashboard");
        orangeTitleBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        getContentPane().add(orangeTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 110));

        dashBoardPanel.setBackground(new java.awt.Color(13, 16, 51));
        dashBoardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel1.setBackground(new java.awt.Color(13, 16, 51));
        menuPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPanel1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel1MouseClicked(evt);
            }
        });

        CRUDPenjualLabel.setBackground(new java.awt.Color(13, 16, 51));
        CRUDPenjualLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CRUDPenjualLabel.setForeground(new java.awt.Color(255, 255, 255));
        CRUDPenjualLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant_50px.png"))); // NOI18N
        CRUDPenjualLabel.setText("CRUD Penjual");

        javax.swing.GroupLayout menuPanel1Layout = new javax.swing.GroupLayout(menuPanel1);
        menuPanel1.setLayout(menuPanel1Layout);
        menuPanel1Layout.setHorizontalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CRUDPenjualLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel1Layout.setVerticalGroup(
            menuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CRUDPenjualLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        dashBoardPanel.add(menuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 210, -1));

        menuPanel2.setBackground(new java.awt.Color(13, 16, 51));
        menuPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPanel2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel2MouseClicked(evt);
            }
        });

        CRUDPembeliLabel.setBackground(new java.awt.Color(13, 16, 51));
        CRUDPembeliLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CRUDPembeliLabel.setForeground(new java.awt.Color(255, 255, 255));
        CRUDPembeliLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budget_50px.png"))); // NOI18N
        CRUDPembeliLabel.setText("CRUD Pembeli");

        javax.swing.GroupLayout menuPanel2Layout = new javax.swing.GroupLayout(menuPanel2);
        menuPanel2.setLayout(menuPanel2Layout);
        menuPanel2Layout.setHorizontalGroup(
            menuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CRUDPembeliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuPanel2Layout.setVerticalGroup(
            menuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CRUDPembeliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        dashBoardPanel.add(menuPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 210, -1));

        menuPanel3.setBackground(new java.awt.Color(13, 16, 51));
        menuPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPanel3MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanel3MouseClicked(evt);
            }
        });

        CRUDKurirLabel.setBackground(new java.awt.Color(13, 16, 51));
        CRUDKurirLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CRUDKurirLabel.setForeground(new java.awt.Color(255, 255, 255));
        CRUDKurirLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motorcycle_delivery_multiple_boxes_50px.png"))); // NOI18N
        CRUDKurirLabel.setText("CRUD Kurir");

        javax.swing.GroupLayout menuPanel3Layout = new javax.swing.GroupLayout(menuPanel3);
        menuPanel3.setLayout(menuPanel3Layout);
        menuPanel3Layout.setHorizontalGroup(
            menuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CRUDKurirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        );
        menuPanel3Layout.setVerticalGroup(
            menuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CRUDKurirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        dashBoardPanel.add(menuPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 210, -1));

        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log-out_35px.png"))); // NOI18N
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        dashBoardPanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 40, 40));

        getContentPane().add(dashBoardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 680));

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));
        whitePanel.setPreferredSize(new java.awt.Dimension(1146, 683));

        javax.swing.GroupLayout whitePanelLayout = new javax.swing.GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        getContentPane().add(whitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1150, 683));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void menuPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel1MousePressed
        menuPanel1.setBackground(clickedColor);
        menuPanel2.setBackground(defaultColor);
        menuPanel3.setBackground(defaultColor);
    }//GEN-LAST:event_menuPanel1MousePressed

    private void menuPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel1MouseClicked
        menuPanel1.setBackground(clickedColor);
        menuPanel2.setBackground(defaultColor);
        menuPanel3.setBackground(defaultColor);
        subTitleLabel.setText("CRUD Penjual");
        
        CRUDPenjual menu1 = new CRUDPenjual();
        whitePanel.removeAll();
        whitePanel.add(menu1).setVisible(true);
    }//GEN-LAST:event_menuPanel1MouseClicked

    private void menuPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel2MouseClicked
        menuPanel1.setBackground(defaultColor);
        menuPanel2.setBackground(clickedColor);
        menuPanel3.setBackground(defaultColor);
        subTitleLabel.setText("CRUD Pembeli");
        
        CRUDPembeli menu2 = new CRUDPembeli();
        whitePanel.removeAll();
        whitePanel.add(menu2).setVisible(true);
    }//GEN-LAST:event_menuPanel2MouseClicked

    private void menuPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel2MousePressed
        menuPanel1.setBackground(defaultColor);
        menuPanel2.setBackground(clickedColor);
        menuPanel3.setBackground(defaultColor);
    }//GEN-LAST:event_menuPanel2MousePressed

    private void menuPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel3MouseClicked
        menuPanel1.setBackground(defaultColor);
        menuPanel2.setBackground(defaultColor);
        menuPanel3.setBackground(clickedColor);
        subTitleLabel.setText("CRUD Kurir");
        
        CRUDKurir menu3 = new CRUDKurir();
        whitePanel.removeAll();
        whitePanel.add(menu3).setVisible(true);
    }//GEN-LAST:event_menuPanel3MouseClicked

    private void menuPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanel3MousePressed
        menuPanel1.setBackground(defaultColor);
        menuPanel2.setBackground(defaultColor);
        menuPanel3.setBackground(clickedColor);
    }//GEN-LAST:event_menuPanel3MousePressed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        LoginPage login1 = new LoginPage();
        login1.show();
        
        dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CRUDKurirLabel;
    private javax.swing.JLabel CRUDPembeliLabel;
    private javax.swing.JLabel CRUDPenjualLabel;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JPanel menuPanel1;
    private javax.swing.JPanel menuPanel2;
    private javax.swing.JPanel menuPanel3;
    private javax.swing.JPanel orangeTitleBar;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JPanel whitePanel;
    // End of variables declaration//GEN-END:variables
}
