
package CourierDashboard;

import SellerDashboard.*;
import BuyerDashboard.*;
import Database.DBNeeds;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

public class PengirimanInternForm extends javax.swing.JInternalFrame {
    private String username;
    private int idPointerKurir;
    private int idPointerPesanan;
    private Boolean isBtn1Clicked = true;
    private Boolean isBtn2Clicked = true;
    LocalDate today = LocalDate.now();
    Date date = java.sql.Date.valueOf(today);
    String dateString = today.toString();

    public PengirimanInternForm(String username) {
        this.username = username;
        idPointerKurir = DBNeeds.getIdKurir(username);
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        fillPesananTable();
        ambilButton.setEnabled(false);
        kirimButton.setEnabled(false);
        selectRow();
    }
    private void selectRow() {
        pesananTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = pesananTable.getSelectedRow();

                    if (selectedRow != -1) {
                        DefaultTableModel model = (DefaultTableModel) pesananTable.getModel();
                        int idPesanan = (Integer)model.getValueAt(selectedRow, 0);
                        System.out.println(idPesanan);
                        idPointerPesanan = idPesanan;
                        ambilButton.setEnabled(true);
                        kirimButton.setEnabled(false);
                    }
                    
                }
            }
        });
    }
    private void fillPesananTable(){
        DefaultTableModel model = (DefaultTableModel) pesananTable.getModel();

        model.setRowCount(0);
        
        String query = "SELECT * FROM pesanan WHERE status_Psnn = 'Selesai diproses'";
        try(Connection connection = DBNeeds.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(query)){
            ResultSet resultSet = preparedStatement.executeQuery();

            while (resultSet.next()) {
                int idPesanan = resultSet.getInt("id_Pesanan");
                String tgl = resultSet.getString("tgl_pesanan");
                String status = resultSet.getString("status_Psnn");
                int idPembeli = resultSet.getInt("id_Pesanan");
                String idKurir = resultSet.getString("id_Kurir");
                int idPenjual = resultSet.getInt("id_Penjual");

                model.addRow(new Object[]{idPesanan, tgl, status, idPembeli,idPenjual, idKurir});
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ambilButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pesananTable = new javax.swing.JTable();
        kirimButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ambilButton.setText("Ambil Pesanan");
        ambilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilButtonActionPerformed(evt);
            }
        });

        pesananTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pesanan", "Tanggal", "Status", "ID Pembeli", "ID Penjual", "ID Kurir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(pesananTable);

        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                    .addComponent(ambilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kirimButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ambilButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kirimButton)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        ambilButton.setEnabled(true);
        kirimButton.setEnabled(false);
        String status= "Pesanan selesai";
        DBNeeds.updateStatusPengiriman(idPointerKurir);
        DBNeeds.updateStatusPesanan(idPointerPesanan, status);
        fillPesananTable();
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void ambilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilButtonActionPerformed
        ambilButton.setEnabled(false);
        kirimButton.setEnabled(true);
        DBNeeds.updateIdKurirPesanan(idPointerKurir, idPointerPesanan);
        DBNeeds.insertPengiriman(idPointerKurir, date);
        fillPesananTable();
    }//GEN-LAST:event_ambilButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambilButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kirimButton;
    private javax.swing.JTable pesananTable;
    // End of variables declaration//GEN-END:variables
}
